### ISSUE TITLE
OSError: matchings/Camera1.txt not found.

### ISSUE THREAD

**Issue by ponyo-cho** [hou-yz/MultiviewX#1]
May I ask for help,,,?
I want to do the Toolkits for MultiviewX dataset.
But Idk what this sentence means that 'copy the 2d/3d simulation annotations into /matchings',
I put the annotations folder .json into /matching，then ‘OSError: matchings/Camera1.txt not found.’，
I modified the .json file to a txt file，then npyio.py 'ValueError: could not convert string to float: '[''...

mabey my thinking is wrong, So what should I do ?

**Comment by hou-yz** [comment]
Thank you for your question.

This repo works as a toolkit for the creation of MultiviewX dataset, and can also be used to inspire related future works. 
Actually, we haven't provided the /matchings folder yet. The original plan was to release the Unity project alongside. However, due to copyright issues, that cannot be done, at least for now. Created from the unity project, the /matchings folder contains /matchings/Camera1.txt files, which records the 2D & 3D bbox info. /annotations_positions folder is the output of run_all.py, an interpreted version of the original 2D & 3D bbox info in the /matchings folder. So, it won't work if you rename it. 

For the time being , I can provide a copy of the /matchings folder at [link](https://anu365-my.sharepoint.com/:u:/g/personal/u6852178_anu_edu_au/EZ9hISq6FxBItIsdIDkapmUBGIK7Fn9LVIAuUT8NltKDBw?e=atMYbI). 

Best,
Yunzhong

**Comment by ponyo-cho** [comment]
> Thank you for your question.
> 
> This repo works as a toolkit for the creation of MultiviewX dataset, and can also be used to inspire related future works.
> Actually, we haven't provided the /matchings folder yet. The original plan was to release the Unity project alongside. However, due to copyright issues, that cannot be done, at least for now. Created from the unity project, the /matchings folder contains /matchings/Camera1.txt files, which records the 2D & 3D bbox info. /annotations_positions folder is the output of run_all.py, an interpreted version of the original 2D & 3D bbox info in the /matchings folder. So, it won't work if you rename it.
> 
> For the time being , I can provide a copy of the /matchings folder at [link](https://anu365-my.sharepoint.com/:u:/g/personal/u6852178_anu_edu_au/EZ9hISq6FxBItIsdIDkapmUBGIK7Fn9LVIAuUT8NltKDBw?e=atMYbI).
> 
> Best,
> Yunzhong

Thank you very much for your reply. 
Also inspired by your excellent work, So I want to restore this scene. Maybe there are still some jobs I need to learn more.
Thanks again for answering my question,thanks for sharing, I will study hard.

Good luck!
Ponyo
